import {
  Box,
  ShoppingCart,
  User,
  Package,
  Settings2,
  BarChart,
  CreditCard,
  Tag,
  Layers,
  FileText,
  Edit,
} from "lucide-react";

export const site_settings = {
  user: {
    name: "Vcomm Admin",
    email: "admin@vcomm.com",
    avatar: "/images/admin.png",
  },
  teams: [
    {
      name: "Vcomm",
      logo: ShoppingCart,
    },
  ],
  navMain: [
    {
      title: "Dashboard",
      url: "#",
      icon: Box,
      isActive: true,
      items: [
        {
          title: "Report",
          url: "/",
        },
        {
          title: "Analytics",
          url: "/",
        },
      ],
    },
    {
      title: "Basic Management",
      url: "#",
      icon: Settings2,
      items: [
        { title: "Language Management", url: "/language-management" },
        { title: "Brand Management", url: "/brands" },
        { title: "Category Management", url: "/categories" },
        { title: "Customization", url: "#" },
        { title: "Regional Management", url: "#" },
        { title: "Services Management", url: "#" },
        { title: "Tax Rates", url: "/tax-rates" },
        { title: "Tax Class", url: "/tax-classes" },
      ],
    },
    {
      title: "Product/Services Management",
      url: "#",
      icon: Package,
      items: [
        { title: "Product List", url: "/products" },
        { title: "Top Trending Products", url: "#" },
        { title: "Recommended Products", url: "#" },
        { title: "Services List", url: "#" },
        { title: "Top Trending Services", url: "#" },
        { title: "Recommended Services", url: "#" },
      ],
    },
    {
      title: "Content Management",
      url: "#",
      icon: Layers,
      items: [
        { title: "General Settings", url: "/general-settings" },
        { title: "Template List", url: "#" },
        { title: "Business Calendar", url: "#" },
        { title: "FAQ", url: "/content/faq" },
      ],
    },
    {
      title: "Vendor Management",
      url: "#",
      icon: User,
      items: [
        { title: "Add Vendor", url: "/vendors/add" },
        { title: "Download Vendor", url: "/vendors/download" },
        { title: "List of Vendors", url: "/vendors" },
      ],
    },
    {
      title: "Customer Management",
      url: "#",
      icon: User,
      items: [
        { title: "User List", url: "#" },
        { title: "Silver Membership", url: "#" },
        { title: "Bronze Membership", url: "#" },
        { title: "Gold Membership", url: "#" },
        { title: "Orders", url: "#" },
        { title: "Coupon", url: "#" },
        { title: "Points", url: "#" },
      ],
    },
    {
      title: "Inventory Management",
      url: "#",
      icon: Package,
      items: [
        { title: "New", url: "#" },
        { title: "Limited", url: "#" },
        { title: "Restock", url: "#" },
        { title: "Campaign", url: "#" },
        { title: "Few Left", url: "#" },
        { title: "Out of Stock", url: "#" },
        { title: "Bulk Upload", url: "#" },
      ],
    },
    {
      title: "Marketing Management",
      url: "#",
      icon: BarChart,
      items: [
        { title: "Campaigns", url: "#" },
        { title: "SEO", url: "#" },
        { title: "Promotions", url: "#" },
        { title: "Social Media", url: "#" },
      ],
    },
    {
      title: "Reports/Analytics",
      url: "#",
      icon: BarChart,
      items: [
        { title: "Sales Reports", url: "#" },
        { title: "Product Performance", url: "#" },
        { title: "Customer Insights", url: "#" },
      ],
    },
    {
      title: "Customer Support",
      url: "#",
      icon: FileText,
      items: [
        { title: "Tickets", url: "#" },
        { title: "Chat Builder", url: "#" },
      ],
    },
    {
      title: "Order Management",
      url: "#",
      icon: ShoppingCart,
      items: [
        { title: "All Orders", url: "#" },
        { title: "Today’s Orders", url: "#" },
        { title: "In Process Orders", url: "#" },
        { title: "Shipped Orders", url: "#" },
        { title: "Cancelled Orders", url: "#" },
        { title: "Returned Orders", url: "#" },
        { title: "Delivered Orders", url: "#" },
        { title: "Pending Orders", url: "#" },
        { title: "Download Order List", url: "#" },
        { title: "Failed Orders", url: "#" },
      ],
    },
    {
      title: "Offer Management",
      url: "#",
      icon: Edit,
      items: [
        { title: "Download Offer List", url: "/offers/download" },
        { title: "Add Offer", url: "/offers/add" },
        { title: "Offer List", url: "/offers" },
      ],
    },
    {
      title: "Coupon Management",
      url: "/coupons",
      icon: Tag,
      items: [
        { title: "Add Coupon", url: "/coupons/add" },
        { title: "List of Coupons", url: "/coupons" },
        { title: "Download Coupon List", url: "/coupons/download" },
      ],
    },
    {
      title: "Packages Management",
      url: "packages",
      icon: Package,
      items: [
        { title: "Add Package", url: "/packages/add" },
        { title: "List of Packages", url: "/packages" },
        { title: "Active Packages", url: "packages?status=active" },
      ],
    },
    {
      title: "Payments",
      url: "#",
      icon: CreditCard,
      items: [
        { title: "Receive Payments for Packages", url: "#" },
        { title: "Receive Payments for Products", url: "#" },
        { title: "Payment History", url: "#" },
        { title: "Refund Payments", url: "#" },
        { title: "Cancel Payments", url: "#" },
        { title: "Payment Distribution", url: "#" },
      ],
    },
    {
      title: "AI-Based Multi Language",
      url: "#",
      icon: Edit,
      items: [],
    },
    {
      title: "Web RTC",
      url: "#",
      icon: FileText,
      items: [],
    },
  ],
};
